### ISSUE TITLE
Doesnt seem to work anymore

### ISSUE THREAD

**Issue by houmie** [Sunnyyoung/SYFavoriteButton#1]
I get two error messages when building it and the button still shows as default.
(I have installed it via Pod)

```
TNNewsView.storyboard: error: IB Designables: Failed to update auto layout status: Failed to load designables from path (null)
```

and

```
TNNewsView.storyboard: error: IB Designables: Failed to render instance of SYFavoriteButton: Failed to load designables from path (null)
```

**Comment by sunnyyoung** [comment]
@houmie Try this way maybe works:
Edit your Podfile like this

```
platform :ios, '7.0'

use_frameworks!
```

**Comment by houmie** [comment]
Ah no. If I do that, it breaks other Pods.

**Comment by sunnyyoung** [comment]
@houmie I have the same problem while using pod contains "IBInspectable" will get two error `Failed to load designables from path (null)`

Finally I drag the `*.h` and `*.m` file to my project, the error disappear
