### ISSUE TITLE
iOS 10 issue

### ISSUE THREAD

**Issue by jhpassion0621** [Sunnyyoung/SYFavoriteButton#4]
If I create this button on storyboard, It doesn't work on iOS 10 now. How can I resolve it?

**Comment by sunnyyoung** [comment]
@jhpassion0621 I tested on my iPhone with iOS 10, it works fine. Did you set the custom class to `SYFavoriteButton`?

**Comment by ghost** [comment]
Same here doesn't work on iOS 10

**Comment by su350380433** [comment]
Same here doesn't work on iOS 10.1

**Comment by ghost** [comment]
Working fine after updating from 10 to 10.1

**Comment by jhpassion0621** [comment]
It works now. Thanks!
